# Generated by Django 4.2.9 on 2024-02-25 16:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_customuser_remove_teacher_class_field_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Studentwenjuan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivation_to_learn', models.IntegerField()),
                ('motivation_evaluation', models.CharField(max_length=50)),
                ('school_motivation_avg', models.FloatField()),
                ('class_motivation_avg', models.FloatField()),
                ('district_motivation_avg', models.FloatField()),
                ('moral_development', models.CharField(max_length=50)),
                ('labor_and_social_practice', models.CharField(max_length=50)),
                ('physical_and_mental_development', models.CharField(max_length=50)),
                ('aesthetic_literacy', models.CharField(max_length=50)),
                ('academic_development', models.CharField(max_length=50)),
                ('current_score', models.FloatField()),
                ('current_score_grade', models.CharField(max_length=50)),
                ('class_avg_score', models.FloatField()),
                ('school_avg_score', models.FloatField()),
                ('district_avg_score', models.FloatField()),
                ('knowledge_internalization', models.CharField(max_length=50)),
                ('chinese_score', models.FloatField()),
                ('chinese_score_evaluation', models.CharField(max_length=50)),
                ('class_avg_chinese_score', models.FloatField()),
                ('school_avg_chinese_score', models.FloatField()),
                ('district_avg_chinese_score', models.FloatField()),
                ('math_score', models.FloatField()),
                ('math_score_evaluation', models.CharField(max_length=50)),
                ('class_avg_math_score', models.FloatField()),
                ('school_avg_math_score', models.FloatField()),
                ('district_avg_math_score', models.FloatField()),
                ('english_score', models.FloatField()),
                ('english_score_evaluation', models.CharField(max_length=50)),
                ('class_avg_english_score', models.FloatField()),
                ('school_avg_english_score', models.FloatField()),
                ('district_avg_english_score', models.FloatField()),
                ('physics_score', models.FloatField()),
                ('physics_score_evaluation', models.CharField(max_length=50)),
                ('class_avg_physics_score', models.FloatField()),
                ('school_avg_physics_score', models.FloatField()),
                ('district_avg_physics_score', models.FloatField()),
                ('history_score_1', models.FloatField()),
                ('history_chinese_score_1', models.FloatField()),
                ('history_math_score_1', models.FloatField()),
                ('history_english_score_1', models.FloatField()),
                ('history_score_2', models.FloatField()),
                ('history_chinese_score_2', models.FloatField()),
                ('history_math_score_2', models.FloatField()),
                ('history_english_score_2', models.FloatField()),
                ('cognitive_intensity', models.FloatField()),
                ('cognitive_intensity_evaluation', models.CharField(max_length=50)),
                ('class_cognitive_intensity', models.FloatField()),
                ('school_cognitive_intensity', models.FloatField()),
                ('district_cognitive_intensity', models.FloatField()),
                ('class_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.class')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.school')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
