# Generated by Django 4.2.9 on 2024-02-26 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goddles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='school',
            field=models.CharField(default='', max_length=50),
        ),
    ]
