# Generated by Django 4.2.9 on 2024-03-06 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goddles', '0003_student_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student_evaluate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
                ('school', models.CharField(max_length=50, verbose_name='学校')),
                ('grade', models.IntegerField(verbose_name='班级')),
                ('moral_development', models.CharField(max_length=10, verbose_name='品德发展')),
                ('labor_and_social_practice', models.CharField(max_length=10, verbose_name='劳动与社会实践')),
                ('physical_and_mental_development', models.CharField(max_length=10, verbose_name='身心发展')),
                ('aesthetic_literacy', models.CharField(max_length=10, verbose_name='审美素养')),
                ('academic_development', models.CharField(max_length=10, verbose_name='学业发展')),
                ('current_grade', models.IntegerField(verbose_name='本次成绩等级')),
                ('internalization_of_knowledge', models.CharField(max_length=10, verbose_name='知识内化')),
                ('chinese_score_evaluation', models.CharField(max_length=10, verbose_name='语文成绩评价')),
                ('math_score_evaluation', models.CharField(max_length=10, verbose_name='数学成绩评价')),
                ('english_score_evaluation', models.CharField(max_length=10, verbose_name='英语成绩评价')),
                ('physics_score_evaluation', models.CharField(max_length=10, verbose_name='物理成绩评价')),
                ('cognitive_intensity', models.IntegerField(verbose_name='认知强度')),
                ('cognitive_intensity_evaluation', models.CharField(max_length=10, verbose_name='认知强度评价')),
                ('class_cognitive_intensity', models.IntegerField(verbose_name='班级认知强度')),
                ('school_cognitive_intensity', models.IntegerField(verbose_name='学校认知强度')),
                ('district_cognitive_intensity', models.IntegerField(verbose_name='区认知强度')),
                ('learning_motivation', models.CharField(max_length=10, verbose_name='学习动机')),
                ('learning_motivation_evaluation', models.CharField(max_length=10, verbose_name='学习动机评价')),
                ('school_motivation_class_average', models.IntegerField(verbose_name='学校动机班级平均分')),
                ('learning_motivation_school_average', models.IntegerField(verbose_name='学习动机学校平均分')),
                ('learning_motivation_district_average', models.IntegerField(verbose_name='学习动机区平均分')),
            ],
        ),
    ]
